Upgrade to new WebRTC Task API
saltyrtc/saltyrtc-demo pull request #6
Opened 2019-03-05 15:32 UTC by lgrahl

Leverages the new SaltyRTC WebRTC Task API.

Further changes:

- Make the user application data channel flow-controlled
- Allow to send arbitrarily sized messages from the web UI
- Allow to send arbitrarily sized messages from the app UI
- Remove redundant utilities
- Cleanup

To do:

- [ ] Web: Use released version of the SaltyRTC WebRTC Task in `package.json` (depends on https://github.com/saltyrtc/saltyrtc-task-webrtc-js/pull/28)
- [ ] Android: Use released version of the SaltyRTC WebRTC Task (depends on https://github.com/saltyrtc/saltyrtc-task-webrtc-java/pull/27)

2019-04-01 17:26 UTC, lgrahl commented
@dbrgn You can start reviewing if you want to. There's an issue with the flow control in the Java version but hopefully that's not going to introduce a lot of changes.

2019-04-02 16:22 UTC, dbrgn requested changes

2019-04-02 16:22 UTC, dbrgn commented on android/app/build.gradle
> +    maven { url "https://dl.bintray.com/saltyrtc/maven" }
All three repos above are not required, since all those libs are submitted to jcenter.

2019-04-02 16:22 UTC, dbrgn commented on android/app/src/main/java/org/saltyrtc/demo/app/StateType.java
> +    SALTY_HANDOVER,
This whitespace change contradicts the .editorconfig file.

2019-04-02 16:22 UTC, dbrgn commented on android/app/src/main/java/org/saltyrtc/demo/app/webrtc/FlowControlledDataChannel.java
> +public class FlowControlledDataChannel {
Lots of mixed tabs and spaces in this class.

2019-04-02 16:22 UTC, dbrgn commented on android/app/src/main/java/org/saltyrtc/demo/app/webrtc/PeerConnectionHelper.java
> +public class PeerConnectionHelper {
Again, mixed tabs and spaces. IIRC you can reformat the file with ctrl+alt+L or something like that.

There are also some other files that use spaces throughout.

2019-04-02 18:59 UTC, lgrahl commented on android/app/src/main/java/org/saltyrtc/demo/app/StateType.java
> +    SALTY_HANDOVER,
I don't know how to tell you that... but there is no .editorconfig file. :smirk: 

But yeah, will reformat all to spaces and add one.

2019-04-02 19:04 UTC, dbrgn commented on android/app/src/main/java/org/saltyrtc/demo/app/StateType.java
> +    SALTY_HANDOVER,
I don't know how to tell you that... but look for yourself :smile: 

![img](https://tmp.dbrgn.ch/screenshots/screenshot-20190402210420-3czhskai.png)

2019-04-02 19:07 UTC, lgrahl commented on android/app/src/main/java/org/saltyrtc/demo/app/StateType.java
> +    SALTY_HANDOVER,
Serves me right for checking the master branch.

2019-04-02 19:23 UTC, lgrahl commented on android/.editorconfig
> +indent_style = tab
Man, what did I copy & paste there... replace this nonsense with https://github.com/saltyrtc/saltyrtc-task-webrtc-java/blob/new-api/.editorconfig

2019-07-09 14:49 UTC, dbrgn commented on android/app/src/main/java/org/saltyrtc/demo/app/webrtc/PeerConnectionHelper.java
> +                        log.warn("Could not feed incoming data", error);
That message is a bit unclear. Is the data hungry? :slightly_smiling_face: 

Maybe this is better?

```suggestion
                        log.warn("Could not feed incoming data to the transport link", error);
```

2019-07-31 08:32 UTC, lgrahl commented on android/app/build.gradle
> +    maven { url "https://dl.bintray.com/saltyrtc/maven" }
Only true for the first.

2019-08-13 10:26 UTC, merged